language: ruby
rvm:
  - 2.7.2
before_install:
  - gem install bundler
addons:
  postgresql: 9.6
before_script:
  - bundle config set --local deployment 'true'
  - bundle install --jobs=3 --retry=3
  - rm -rf spec/fixtures/vcr_cassettes
script:
  - bundle exec rails db:{create,migrate} RAILS_ENV=test
  - bundle exec rspec
